### ISSUE TITLE
SEDI scraper

### ISSUE THREAD

**Issue by jpmckinney** [drouetd/canbiz#1]
Hey Daniel, I was considering scraping SEDI as a potential source for an influence mapping project, and found your repository by searching GitHub. I see the code is in progress, but would it be possible to run `scraper_sedi.py` and get a database with a copy of the information available at sedi.ca on insiders?

**Comment by drouetd** [comment]
Hi James,

The answer is yes... with a little work. Btw, the code is part of a project I'm doing for [Ajah](www.ajah.ca) (Mike is fine with you using it for non-commercial purposes but a nod to Ajah would be appreciated if you go ahead with your project). Assuming you want to get all the companies and their associated insiders so you can run queries, you'll need to do the following:

1. Create a postgres database and enter the connection parameters in `settings.py` DATABASE.

2. Set up a virtualenv as per `requirements.txt` 

3. Run  `python models.py` to set up the database tables.

4. `scraper_sedy.py` gets the list of companies to scrape from the database table `Company`, so you can either populate that manually (you only need to fill in the company name field) if you are only interested in a small number of companies. If you want all companies traded on the TSX you'll need step 5 instead.

5. Run `python scraper_tmx.py`. 
(Note that there is a list variable `index` that must be set. If `index = ['A', 'B', 'C']`, then only companies whose stock symbol begins with 'A', 'B', 'C' will be added to the database. To get all the companies you'll need all the letters of the alphabet + '0-9').

6. Now from `scraper_sedi.py` you simply need to run functions `add_issuer_numbers_to_db()`, `add_insiders_to_db()` and `add_positions_to_db()` one after the other to grab the insiders associated with the companies identified in steps 4/5.  

At this point you should be good to go. If you want to use the code you should probably grab it soon as I'll be moving it to a private repo later this week. Alternatively, you could ask Mike for a database dump in a month or so when we have the project up and running :-)

**Comment by jpmckinney** [comment]
Thanks!
